import type { Locale } from '../../i18n/index.ts';

export const searchCopy = {
  'zh-hant': {
    title: '全站搜尋',
    intro: '搜尋文章、筆記與網站頁面的標題、摘要、標籤和正文。',
    placeholder: '搜尋 P2P、藥理、Rust…',
    submit: '搜尋',
    filter: '內容類型',
    tagFilter: '標籤',
    allTags: '全部標籤',
    all: '全部',
    article: '文章',
    note: '筆記',
    page: '頁面',
    loading: '正在載入搜尋內容…',
    error: '搜尋內容載入失敗，請重試。',
    retry: '重試',
    clear: '清除搜尋',
    empty: '沒有符合的結果',
    emptyHint: '試試較短的關鍵字，或選擇全部內容類型與標籤。',
    browse: '輸入關鍵字，或瀏覽下列已發布內容。',
    noJs: '搜尋需要 JavaScript；仍可透過下方連結瀏覽首頁、文章與筆記。',
    fallback: '目前語言尚無譯文，開啟原文',
    count: (n: number) => `${n} 筆結果`,
    home: '首頁',
    blog: '部落格',
    notes: '筆記',
  },
  en: {
    title: 'Search the site',
    intro:
      'Search titles, summaries, tags and full text across articles, notes and site pages.',
    placeholder: 'Search P2P, pharmacology, Rust…',
    submit: 'Search',
    filter: 'Content type',
    tagFilter: 'Tag',
    allTags: 'All tags',
    all: 'All',
    article: 'Article',
    note: 'Note',
    page: 'Page',
    loading: 'Loading searchable content…',
    error: 'Search content could not be loaded. Please try again.',
    retry: 'Try again',
    clear: 'Clear search',
    empty: 'No matching results',
    emptyHint: 'Try a shorter keyword or select all content types and tags.',
    browse: 'Enter a keyword or browse the published content below.',
    noJs: 'Search needs JavaScript. You can still browse the home page, articles and notes using the links below.',
    fallback: 'No translation in this language yet; opens the original',
    count: (n: number) => `${n} result${n === 1 ? '' : 's'}`,
    home: 'Home',
    blog: 'Blog',
    notes: 'Notes',
  },
  ja: {
    title: 'サイト内検索',
    intro:
      '記事・ノート・サイト内ページのタイトル、概要、タグ、本文を検索します。',
    placeholder: 'P2P、薬理、Rust などを検索…',
    submit: '検索',
    filter: 'コンテンツの種類',
    tagFilter: 'タグ',
    allTags: 'すべてのタグ',
    all: 'すべて',
    article: '記事',
    note: 'ノート',
    page: 'ページ',
    loading: '検索データを読み込んでいます…',
    error: '検索データを読み込めませんでした。再試行してください。',
    retry: '再試行',
    clear: '検索をクリア',
    empty: '一致する結果はありません',
    emptyHint: '短いキーワードを使うか、すべての種類とタグを選んでください。',
    browse: 'キーワードを入力するか、下の公開コンテンツをご覧ください。',
    noJs: '検索には JavaScript が必要です。下のリンクからホーム、記事、ノートをご覧いただけます。',
    fallback: 'この言語の翻訳はまだありません。原文を開きます',
    count: (n: number) => `${n} 件の結果`,
    home: 'ホーム',
    blog: 'ブログ',
    notes: 'ノート',
  },
} satisfies Record<Locale, object>;
